#!/usr/bin/env python3
"""AsyncReview CLI - Review GitHub PRs and Issues from the command line.

Primary use case: PR code review with full diff context.

Examples:
    # Quick PR review
    asyncreview review --url https://github.com/org/repo/pull/123 -q "Any security concerns?"
    
    # Output as markdown for docs
    asyncreview review --url https://github.com/org/repo/pull/123 -q "Summarize changes" --output markdown
    
    # Quiet mode for scripting
    asyncreview review --url https://github.com/org/repo/pull/123 -q "Review this" --quiet --output json
"""

import argparse
import asyncio
import sys

from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

from . import __version__
from .github_fetcher import parse_github_url, post_comment
from .local_fetcher import validate_local_path
from .output_formatter import format_output
from .virtual_runner import VirtualReviewRunner
from .expert_prompts import get_expert_prompt


console = Console()


def print_step(step_num: int, reasoning: str, code: str, output: str = ""):
    """Print RLM step progress (when not in quiet mode)."""
    from rich.syntax import Syntax
    
    console.print(f"\n[cyan]Step {step_num}[/cyan]", style="bold")
    
    # Show reasoning
    if reasoning:
        reasoning_display = reasoning[:800] + "..." if len(reasoning) > 800 else reasoning
        console.print(f"[dim]💭 {reasoning_display}[/dim]")
    
    # Show executed code with syntax highlighting
    if code and code.strip():
        code_display = code[:2000] if len(code) > 2000 else code
        console.print("\n[yellow]📝 Code:[/yellow]")
        syntax = Syntax(code_display, "python", theme="monokai", line_numbers=False)
        console.print(syntax)
    
    # Show output (truncated)
    if output and output.strip():
        output_display = output[:500] + "..." if len(output) > 500 else output
        console.print(f"\n[green]📤 Output:[/green] [dim]{output_display}[/dim]")


def print_info(message: str):
    """Print an info message."""
    console.print(f"[dim]{message}[/dim]")


def print_error(message: str):
    """Print an error message."""
    console.print(f"[red]Error: {message}[/red]")


async def run_review(
    url: str,
    question: str | None = None,
    output_format: str = "text",
    quiet: bool = False,
    model: str | None = None,
    expert: bool = False,
    submit: bool = False,
):
    """Run a review on a GitHub URL."""
    # Parse URL first to validate
    try:
        owner, repo, number, url_type = parse_github_url(url)
    except ValueError as e:
        print_error(str(e))
        sys.exit(1)
    
    # Determine the question to use
    if expert:
        actual_question = get_expert_prompt(question)
        review_mode = "Expert Review"
    elif question:
        actual_question = question
        review_mode = "Review"
    else:
        print_error("Either --question or --expert is required")
        sys.exit(1)
    
    if not quiet:
        type_label = "PR" if url_type == "pr" else "Issue"
        print_info(f"Reviewing {type_label}: {owner}/{repo}#{number}")
        if expert:
            print_info(f"Mode: Expert Code Review (SOLID, Security, Code Quality)")
        else:
            print_info(f"Question: {actual_question}")
        console.print()
    
    # Create runner
    runner = VirtualReviewRunner(
        model=model,
        quiet=quiet,
        on_step=None if quiet else print_step,
    )
    
    try:
        answer, sources, metadata = await runner.review(url, actual_question)
    except Exception as e:
        print_error(f"Review failed: {e}")
        sys.exit(1)
    
    # Format and print output
    model_name = metadata.get("model", model or "unknown")
    output = format_output(
        answer=answer,
        sources=sources,
        model=model_name,
        output_format=output_format,
        metadata=metadata if output_format == "json" else None,
    )
    
    if quiet or output_format == "json":
        # Raw output for scripting
        print(output)
    else:
        # Rich formatted output
        console.print()
        if output_format == "markdown":
            console.print(Panel(Markdown(output), title="Review", border_style="green"))
        else:
            console.print(Panel(output, title="Review", border_style="green"))
    
    # Submit as GitHub comment if requested
    if submit:
        try:
            # Format review as markdown for GitHub comment
            comment_body = f"## 🔍 AsyncReview Analysis\n\n{answer}\n\n---\n*Generated by [AsyncReview](https://github.com/AsyncFuncAI/AsyncReview) using {model_name}*"
            result = await post_comment(owner, repo, number, comment_body)
            if not quiet:
                console.print(f"\n[green]✓ Comment posted:[/green] {result.get('html_url', 'success')}")
        except ValueError as e:
            print_error(str(e))
            sys.exit(1)
        except Exception as e:
            print_error(f"Failed to post comment: {e}")
            sys.exit(1)


async def run_local_review(
    path: str,
    question: str | None = None,
    output_format: str = "text",
    quiet: bool = False,
    model: str | None = None,
    expert: bool = False,
):
    """Run a review on a local directory."""
    # Validate path first
    try:
        abs_path = validate_local_path(path)
    except ValueError as e:
        print_error(str(e))
        sys.exit(1)

    # Determine the question to use
    if expert:
        actual_question = get_expert_prompt(question)
        review_mode = "Expert Review"
    elif question:
        actual_question = question
        review_mode = "Review"
    else:
        print_error("Either --question or --expert is required")
        sys.exit(1)

    if not quiet:
        print_info(f"Reviewing local directory: {abs_path}")
        if expert:
            print_info(f"Mode: Expert Code Review (SOLID, Security, Code Quality)")
        else:
            print_info(f"Question: {actual_question}")
        console.print()

    # Create runner
    runner = VirtualReviewRunner(
        model=model,
        quiet=quiet,
        on_step=None if quiet else print_step,
    )

    try:
        answer, sources, metadata = await runner.review_local(abs_path, actual_question)
    except Exception as e:
        print_error(f"Review failed: {e}")
        sys.exit(1)

    # Format and print output
    model_name = metadata.get("model", model or "unknown")
    output = format_output(
        answer=answer,
        sources=sources,
        model=model_name,
        output_format=output_format,
        metadata=metadata if output_format == "json" else None,
    )

    if quiet or output_format == "json":
        # Raw output for scripting
        print(output)
    else:
        # Rich formatted output
        console.print()
        if output_format == "markdown":
            console.print(Panel(Markdown(output), title="Review", border_style="green"))
        else:
            console.print(Panel(output, title="Review", border_style="green"))


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="AsyncReview CLI - Review GitHub PRs and Issues",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  asyncreview review --url https://github.com/org/repo/pull/123 -q "Any risks?"
  asyncreview review --url https://github.com/org/repo/issues/42 -q "What's needed?" --output markdown
  asyncreview review --url <url> -q "Review" --quiet --output json
        """,
    )
    
    parser.add_argument(
        "--version", "-V",
        action="version",
        version=f"asyncreview {__version__}",
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # review command
    review_parser = subparsers.add_parser(
        "review",
        help="Review a GitHub PR/Issue or local directory",
    )

    # URL and path are mutually exclusive
    source_group = review_parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--url", "-u",
        type=str,
        help="GitHub PR or Issue URL",
    )
    source_group.add_argument(
        "--path", "-p",
        type=str,
        help="Local directory path to review",
    )

    review_parser.add_argument(
        "--question", "-q",
        type=str,
        required=False,
        default=None,
        help="Question to ask about the PR/Issue/directory (optional with --expert)",
    )
    review_parser.add_argument(
        "--expert",
        action="store_true",
        help="Run expert code review (SOLID, Security, Performance, Code Quality)",
    )
    review_parser.add_argument(
        "--output", "-o",
        type=str,
        choices=["text", "markdown", "json"],
        default="text",
        help="Output format (default: text)",
    )
    review_parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress progress output, print only the result",
    )
    review_parser.add_argument(
        "--model", "-m",
        type=str,
        default=None,
        help="Model to use (e.g. gemini-3.0-pro-preview)",
    )
    review_parser.add_argument(
        "--submit",
        action="store_true",
        help="Post review as a comment on the PR/Issue (GitHub only, requires GITHUB_TOKEN)",
    )

    args = parser.parse_args()

    if args.command == "review":
        # Validate --submit is only used with --url
        if args.submit and args.path:
            print_error("--submit can only be used with --url (GitHub reviews)")
            sys.exit(1)

        # Dispatch to appropriate review function
        if args.url:
            asyncio.run(run_review(
                url=args.url,
                question=args.question,
                output_format=args.output,
                quiet=args.quiet,
                model=args.model,
                expert=args.expert,
                submit=args.submit,
            ))
        elif args.path:
            asyncio.run(run_local_review(
                path=args.path,
                question=args.question,
                output_format=args.output,
                quiet=args.quiet,
                model=args.model,
                expert=args.expert,
            ))
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
